name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:${{ github.sha }} .

      - name: Push Docker image with SHA tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:${{ github.sha }}

      - name: Tag image as latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/my-node-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      - name: Push latest tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
